spring.application.name=sampleClg

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d1nom5be5dus73b4pgv0-a.oregon-postgres.render.com/skillfirstlab_afxb
spring.datasource.username=hari
spring.datasource.password=AHKz9ejAiYglZn2yAzXzNopOdRJHQ4EP
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.jpa.show-sql=true
