#For more secured projects we use  high secured software
spring.application.name=StudentManagementSystem
# === PostgreSQL Cloud DB Connection ===
spring.datasource.url=jdbc:postgresql://dpg-d1n7pkeuk2gs739miamg-a.singapore-postgres.render.com:5432/studentdb_h96v
spring.datasource.username=admin
spring.datasource.password=iLrxrUitCzT6wxrpGI0Az0QdBLTOy4Ft
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional server port
server.port=8080


